### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by prfafQA** [QuakedK/Oneclick#1]
Hello, it is possible to restore processes without a backup, because it deleted itself and does not want to reset the computer, and it needs processes to run important programs.

**Comment by shahtirth07** [comment]
Open Task Scheduler (taskschd.msc from Run dialog).
Review any tasks that may have been set to run automatically and could help recreate your processes.
Re-enable any that are relevant or have become disabled

**Comment by QuakedK** [comment]
# Restore point usage

You mention solving you're issue without using a backup/restore point and also say how it managed to delete itself. 
Now I'm quite positive you're not being entirely truthful, as restore points don't studdenly vanish. We recommend restore points for these very scenarios. It is however possible the restore point is hidden, try going to [Advanced recovery](https://www.youtube.com/watch?v=EuI7HFppgEM) and seeing if the system restore point is there. If you didn't create or see you're restore point, you can click Winkey + R then type services.msc into the run box. Once there you can find any service you may need and right click them then select properties, then click on the start up type and change it to automatic. You can also try running [ Xbox Service Enabler](https://github.com/QuakedK/Downloads/blob/main/1-%20Xbox%20Service%20Enabler.bat) as admin since it reenables a lot of different services and it might be of help. You also mentioned not being to reset, while due to the extreme debloating nature some windows settings and feature don't work like reset my pc. You can try doing so in advanced recovery or getting a usb and reinstalling windows that way.

Hope this helps!

**Comment by QuakedK** [comment]
> Hello, it is possible to restore processes without a backup, because it deleted itself and does not want to reset the computer, and it needs processes to run important programs.

# Restore point usage

You mention solving you're issue without using a backup/restore point and also say how it managed to delete itself. 
Now I'm quite positive you're not being entirely truthful, as restore points don't studdenly vanish. We recommend restore points for these very scenarios. It is however possible the restore point is hidden, try going to [Advanced recovery](https://www.youtube.com/watch?v=EuI7HFppgEM) and seeing if the system restore point is there. If you didn't create or see you're restore point, you can click Winkey + R then type services.msc into the run box. Once there you can find any service you may need and right click them then select properties, then click on the start up type and change it to automatic. You can also try running [ Xbox Service Enabler](https://github.com/QuakedK/Downloads/blob/main/1-%20Xbox%20Service%20Enabler.bat) as admin since it reenables a lot of different services and it might be of help. You also mentioned not being to reset, while due to the extreme debloating nature some windows settings and feature don't work like reset my pc. You can try doing so in advanced recovery or getting a usb and reinstalling windows that way.

Hope this helps!

**Comment by prfafQA** [comment]
Hello, thank you for your help, I'll let you know if it helped.

**Comment by prfafQA** [comment]
Hello, unfortunately I can't turn on these processes. Do you have a script that activates them?
